#referenceï¼š https://www.ruanyifeng.com/blog/2019/09/getting-started-with-github-actions.html
name: Deploy To Github Pages
run-name: Deploy To Github Pages ğŸš€
on:
  push:
    branches:
      - develop # æŒ‡å®šåŠ¨ä½œä¸‹ ä¼šè¿è¡Œ workflow
jobs:
  Explore-GitHub-Actions:
    name: Deploy To Github Pages
    runs-on: ubuntu-latest # runs-onå­—æ®µæŒ‡å®šè¿è¡Œæ‰€éœ€è¦çš„è™šæ‹Ÿæœºç¯å¢ƒã€‚å®ƒæ˜¯å¿…å¡«å­—æ®µ
    steps:
      # step 1
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Meng
          MIDDLE_NAME: _
          LAST_NAME: Nico
        run: |
         echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      # step 2
      - name: Checkout
        uses: actions/checkout@master
      # step 3
      - name: Install and Build ğŸ”§
        run: |
          npm install --force
          npm run build
       # step 4
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: github-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.

      - run: echo "ğŸ This job's status is ${{ job.status }}."
